[package]
name = "nxml"
version = "0.1.0"
edition = "2021"
description = "A parser for NXML (NXML is not XML!)"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
print_return_values = "0.2.0"
